import type { Metadata } from 'next';
import { Provider } from '@/ui/provider';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import React from 'react';
import { UserInfoBlock } from '@/components/UserInfo/UserInfoBlock';
import UserInfoProvider from '@/components/UserInfo/UserInfoContext';
import Header from '@/components/Header/Header';
import packageJson from '../../package.json';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Leonardo AI project',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <UserInfoProvider>
            <UserInfoBlock>
              <header className="row-start-1 flex items-center justify-between w-full max-w-3xl">
                <Header />
              </header>
              {children}
            </UserInfoBlock>
            <footer >
              current challenge version: {packageJson.version || 'unknown'}
            </footer>
          </UserInfoProvider>
        </Provider>
      </body>
    </html>
  );
}
